# Generated by Django 3.2.25 on 2024-06-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=255)),
                ('m_date', models.DateField()),
                ('E_date', models.DateField()),
            ],
        ),
    ]
